# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 402)
        self.defaultBt = QtWidgets.QPushButton(Dialog)
        self.defaultBt.setGeometry(QtCore.QRect(9, 343, 75, 23))
        self.defaultBt.setObjectName("defaultBt")
        self.saveBt = QtWidgets.QPushButton(Dialog)
        self.saveBt.setGeometry(QtCore.QRect(113, 343, 128, 23))
        self.saveBt.setObjectName("saveBt")
        self.minAccuracyLabel = QtWidgets.QLabel(Dialog)
        self.minAccuracyLabel.setGeometry(QtCore.QRect(9, 28, 79, 16))
        self.minAccuracyLabel.setObjectName("minAccuracyLabel")
        self.minAccuracyTE = QtWidgets.QLineEdit(Dialog)
        self.minAccuracyTE.setGeometry(QtCore.QRect(113, 28, 128, 20))
        self.minAccuracyTE.setObjectName("minAccuracyTE")
        self.minSampleLenLabel = QtWidgets.QLabel(Dialog)
        self.minSampleLenLabel.setGeometry(QtCore.QRect(9, 73, 94, 16))
        self.minSampleLenLabel.setObjectName("minSampleLenLabel")
        self.minSampleLenTE = QtWidgets.QLineEdit(Dialog)
        self.minSampleLenTE.setGeometry(QtCore.QRect(113, 73, 128, 20))
        self.minSampleLenTE.setObjectName("minSampleLenTE")
        self.maxSampleLenLabel = QtWidgets.QLabel(Dialog)
        self.maxSampleLenLabel.setGeometry(QtCore.QRect(9, 118, 98, 16))
        self.maxSampleLenLabel.setObjectName("maxSampleLenLabel")
        self.maxSampleLenTE = QtWidgets.QLineEdit(Dialog)
        self.maxSampleLenTE.setGeometry(QtCore.QRect(113, 118, 128, 20))
        self.maxSampleLenTE.setObjectName("maxSampleLenTE")
        self.silenceThresholdLabel = QtWidgets.QLabel(Dialog)
        self.silenceThresholdLabel.setGeometry(QtCore.QRect(9, 163, 98, 16))
        self.silenceThresholdLabel.setObjectName("silenceThresholdLabel")
        self.silenceThresholdTE = QtWidgets.QLineEdit(Dialog)
        self.silenceThresholdTE.setGeometry(QtCore.QRect(113, 163, 128, 20))
        self.silenceThresholdTE.setObjectName("silenceThresholdTE")
        self.samplingRateLabel = QtWidgets.QLabel(Dialog)
        self.samplingRateLabel.setGeometry(QtCore.QRect(9, 208, 67, 16))
        self.samplingRateLabel.setObjectName("samplingRateLabel")
        self.samplingRateTE = QtWidgets.QLineEdit(Dialog)
        self.samplingRateTE.setGeometry(QtCore.QRect(113, 208, 128, 20))
        self.samplingRateTE.setObjectName("samplingRateTE")
        self.minSilenceLenLabel = QtWidgets.QLabel(Dialog)
        self.minSilenceLenLabel.setGeometry(QtCore.QRect(9, 253, 90, 16))
        self.minSilenceLenLabel.setObjectName("minSilenceLenLabel")
        self.minSilenceLenTE = QtWidgets.QLineEdit(Dialog)
        self.minSilenceLenTE.setGeometry(QtCore.QRect(113, 253, 128, 20))
        self.minSilenceLenTE.setObjectName("minSilenceLenTE")
        self.keepSilenceLabel = QtWidgets.QLabel(Dialog)
        self.keepSilenceLabel.setGeometry(QtCore.QRect(9, 298, 77, 16))
        self.keepSilenceLabel.setObjectName("keepSilenceLabel")
        self.keepSilenceTE = QtWidgets.QLineEdit(Dialog)
        self.keepSilenceTE.setGeometry(QtCore.QRect(113, 298, 128, 20))
        self.keepSilenceTE.setObjectName("keepSilenceTE")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.defaultBt.setText(_translate("Dialog", "Default"))
        self.saveBt.setText(_translate("Dialog", "Save"))
        self.minAccuracyLabel.setText(_translate("Dialog", "min_accuracy %"))
        self.minAccuracyTE.setText(_translate("Dialog", "60"))
        self.minSampleLenLabel.setText(_translate("Dialog", "min_sample_len sec"))
        self.minSampleLenTE.setText(_translate("Dialog", "5"))
        self.maxSampleLenLabel.setText(_translate("Dialog", "max_sample_len sec"))
        self.maxSampleLenTE.setText(_translate("Dialog", "25"))
        self.silenceThresholdLabel.setText(_translate("Dialog", "silence_threshold db"))
        self.silenceThresholdTE.setText(_translate("Dialog", "-50"))
        self.samplingRateLabel.setText(_translate("Dialog", "sampling_rate"))
        self.samplingRateTE.setText(_translate("Dialog", "22050"))
        self.minSilenceLenLabel.setText(_translate("Dialog", "min_silence_len ms"))
        self.minSilenceLenTE.setText(_translate("Dialog", "800"))
        self.keepSilenceLabel.setText(_translate("Dialog", "keep_silence ms"))
        self.keepSilenceTE.setText(_translate("Dialog", "400"))
